name: COF-site

x-coffeeshop-app: &coffeeshop-app
  build:
    context: .
    dockerfile: Dockerfile

services:
  postgres:
    image: postgres:17-alpine
    container_name: cof_db
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${DATABASE_NAME}
      - POSTGRES_USER=${DATABASE_USERNAME}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
    networks:
      - dbnet
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DATABASE_USERNAME} -d ${DATABASE_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s

  coffeeshop-migrations:
    <<: *coffeeshop-app
    env_file:
      - .env
    environment:
      - DATABASE_HOST=${DATABASE_HOST}
      - DATABASE_PORT=${DATABASE_PORT}
    working_dir: /app/coffeeshop
    networks:
      - dbnet
    depends_on:
      postgres:
        condition: service_healthy
    command: python manage.py migrate

  coffeeshop:
    <<: *coffeeshop-app
    env_file:
      - .env
    environment:
      - DATABASE_HOST=${DATABASE_HOST}
      - DATABASE_PORT=${DATABASE_PORT}
    working_dir: /app/coffeeshop
    networks:
      - dbnet
    depends_on:
      postgres:
        condition: service_healthy
      coffeeshop-migrations:
        condition: service_completed_successfully
    command: gunicorn -c gunicorn.py config.wsgi

  nginx:
    image: nginx:1.27-alpine
    container_name: nginx-server
    restart: always
    networks:
      - dbnet
    ports:
      - "80:8088"
    volumes:
      - ./coffeeshop/static:/app/www/coffeeshop/static
      - ./coffeeshop/media:/app/www/coffeeshop/media
      - ./coffeeshop/logs:/app/www/coffeeshop/logs
      - ./nginx:/etc/nginx/conf.d
    depends_on:
      - coffeeshop


networks:
  dbnet:
    driver: bridge


volumes:
  postgres_data:
