name: COF-test

x-test-coffeeshop-app: &test-coffeeshop-app
  build:
    context: .
    dockerfile: Dockerfile
    args:
      INSTALL_DEV_DEPS: "true"

services:
  test-postgres:
    image: postgres:17-alpine
    container_name: test_cof_db
    restart: always
    ports:
      - "8397:5432"
    volumes:
      - postgres_test_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${DATABASE_NAME}
      - POSTGRES_USER=${DATABASE_USERNAME}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
    networks:
      - test_dbnet
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DATABASE_USERNAME} -d ${DATABASE_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s

  test-coffeeshop-migrations:
    <<: *test-coffeeshop-app
    env_file:
      - .env
    working_dir: /app/coffeeshop
    environment:
      - DATABASE_HOST=${TEST_DATABASE_HOST}
      - DATABASE_PORT=${DATABASE_PORT}
    networks:
      - test_dbnet
    depends_on:
      test-postgres:
        condition: service_healthy
    command: python manage.py migrate

  test-coffeeshop-lint:
    <<: *test-coffeeshop-app
    env_file:
      - .env
    environment:
      - DATABASE_HOST=${TEST_DATABASE_HOST}
      - DATABASE_PORT=${DATABASE_PORT}
    networks:
      - test_dbnet
    depends_on:
      test-postgres:
        condition: service_healthy
      test-coffeeshop-migrations:
        condition: service_completed_successfully
    command: sh -c "ruff format && ruff check"

  test-coffeeshop:
    <<: *test-coffeeshop-app
    env_file:
      - .env
    environment:
      - DATABASE_HOST=${TEST_DATABASE_HOST}
      - DATABASE_PORT=${DATABASE_PORT}
    volumes:
      - ./tests:/app/tests
      - ./pytest.ini:/app/pytest.ini
    networks:
      - test_dbnet
    depends_on:
      test-postgres:
        condition: service_healthy
      test-coffeeshop-migrations:
        condition: service_completed_successfully
    command: pytest -v


networks:
  test_dbnet:
    driver: bridge


volumes:
  postgres_test_data: