# Generated by Django 5.2 on 2025-06-07 18:40
from __future__ import annotations

from decimal import Decimal

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="order",
            options={"ordering": ["-time_created"], "verbose_name": "Order", "verbose_name_plural": "Orders"},
        ),
        migrations.AlterModelOptions(
            name="orderitem",
            options={"verbose_name": "Order Item", "verbose_name_plural": "Order Items"},
        ),
        migrations.AlterField(
            model_name="order",
            name="delivery_address",
            field=models.TextField(verbose_name="Delivery Address"),
        ),
        migrations.AlterField(
            model_name="order",
            name="is_paid",
            field=models.BooleanField(default=False, verbose_name="Paid"),
        ),
        migrations.AlterField(
            model_name="order",
            name="phone",
            field=models.CharField(max_length=20, verbose_name="Phone"),
        ),
        migrations.AlterField(
            model_name="order",
            name="time_created",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Creation Date"),
        ),
        migrations.AlterField(
            model_name="order",
            name="total_price",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(Decimal("0.01"))],
                verbose_name="Total Amount",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name="User"
            ),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="order.order",
                verbose_name="Order",
            ),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="price",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(Decimal("0.01"))],
                verbose_name="Price",
            ),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="product_id",
            field=models.PositiveIntegerField(verbose_name="Product ID"),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="product_name",
            field=models.CharField(max_length=255, verbose_name="Product Name"),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="quantity",
            field=models.PositiveIntegerField(
                validators=[django.core.validators.MinValueValidator(1)], verbose_name="Quantity"
            ),
        ),
    ]
