# Generated by Django 5.2 on 2025-07-18 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_alter_order_options_alter_orderitem_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='applied_promo_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Applied promo'),
        ),
        migrations.AddField(
            model_name='order',
            name='applied_promo_status',
            field=models.BooleanField(default=False, verbose_name='Applied promo status Y/N'),
        ),
    ]
