# Generated by Django 5.2.4 on 2025-08-02 18:35
from __future__ import annotations

from decimal import Decimal

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0003_order_applied_promo_name_order_applied_promo_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="cart_price",
            field=models.DecimalField(
                decimal_places=2,
                default=0.01,
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(Decimal("0.01"))],
                verbose_name="Cart Total",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="discount_sum",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name="Discount SUM"),
        ),
    ]
