# Generated by Django 5.2.4 on 2025-08-02 18:37

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_order_cart_price_order_discount_sum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='cart_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Cart Total'),
        ),
    ]
