# Generated by Django 5.2 on 2025-06-26 16:51
from __future__ import annotations

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("catalog", "0011_alter_product_options_alter_productcategory_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="CartTotalDiscount",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=250)),
                ("description", models.TextField()),
                ("is_active", models.BooleanField(default=False)),
                ("date_start", models.DateTimeField()),
                ("date_end", models.DateTimeField()),
                ("min_cart_total", models.DecimalField(decimal_places=2, max_digits=10)),
                ("discount", models.DecimalField(decimal_places=2, max_digits=4)),
            ],
            options={
                "verbose_name": "Cart Total Discount Promo",
                "verbose_name_plural": "Cart Total Discount Promos",
            },
        ),
        migrations.CreateModel(
            name="FreeProductPromo",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=250)),
                ("description", models.TextField()),
                ("is_active", models.BooleanField(default=False)),
                ("date_start", models.DateTimeField()),
                ("date_end", models.DateTimeField()),
                ("required_promo_products", models.PositiveIntegerField(default=2)),
                ("free_promo_products", models.PositiveIntegerField(default=1)),
                ("promo_products", models.ManyToManyField(related_name="free_product_promos", to="catalog.product")),
            ],
            options={
                "verbose_name": "Cart Free Product Promo",
                "verbose_name_plural": "Cart Free Product Promos",
            },
        ),
    ]
