# Generated by Django 5.2 on 2025-07-04 18:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_alter_product_options_alter_productcategory_options'),
        ('promo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('description', models.TextField()),
                ('is_active', models.BooleanField(default=False)),
                ('date_start', models.DateTimeField()),
                ('date_end', models.DateTimeField()),
                ('min_cart_total', models.DecimalField(decimal_places=2, default=1.0, max_digits=10)),
                ('required_products_quantity', models.PositiveIntegerField(default=2)),
                ('free_promo_products', models.PositiveIntegerField(default=0)),
                ('discount', models.DecimalField(decimal_places=2, default=0.0, max_digits=4)),
                ('promo_products', models.ManyToManyField(related_name='free_product_promos', to='catalog.product')),
                ('promo_type', models.IntegerField(choices=[(1, 'Total Cart'), (2, 'Free Product')], default=1)),
            ],
            options={
                'verbose_name': 'Cart Promo',
                'verbose_name_plural': 'Cart Promos',
                'ordering': ['is_active', '-date_start'],
            },
        ),
        # migrations.CreateModel(
        #     name='PromoType',
        #     fields=[
        #         ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        #         ('name', models.CharField(max_length=100)),
        #     ],
        # ),
        migrations.DeleteModel(
            name='CartTotalDiscount',
        ),
        # migrations.AddField(
        #     model_name='promo',
        #     name='promo_type',
        #     field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='promo_types', to='promo.promotype'),
        # ),
        migrations.DeleteModel(
            name='FreeProductPromo',
        ),
    ]
