# Generated by Django 5.2 on 2025-07-18 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promo', '0002_promo_promotype_delete_carttotaldiscount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promo',
            name='min_cart_total',
            field=models.DecimalField(decimal_places=2, default=0.01, max_digits=16),
        ),
        migrations.AlterField(
            model_name='promo',
            name='required_products_quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
