# Generated by Django 5.2.4 on 2025-08-02 14:35
from __future__ import annotations

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("promo", "0003_alter_promo_min_cart_total_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="promo",
            name="promo_type",
            field=models.IntegerField(blank=True, choices=[(1, "TOTAL_CART"), (2, "FREE_PRODUCT")], default=0),
        ),
        # migrations.DeleteModel(
        #     name='PromoType',
        # ),
    ]
