# Generated by Django 5.2.4 on 2025-08-02 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promo', '0004_alter_promo_promo_type_delete_promotype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promo',
            name='promo_type',
            field=models.IntegerField(choices=[(1, 'TOTAL_CART'), (2, 'FREE_PRODUCT')]),
        ),
    ]
