# Generated by Django 5.1.7 on 2025-04-04 11:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_category_manufacture_region_sort_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cats', to='catalog.category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='manufacture',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='manufacturers', to='catalog.manufacture'),
        ),
        migrations.AlterField(
            model_name='product',
            name='region',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='regions', to='catalog.region'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sort',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sorts', to='catalog.sort'),
        ),
        migrations.AlterField(
            model_name='product',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='types', to='catalog.type'),
        ),
    ]
