# Generated by Django 5.2 on 2025-04-28 18:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_product_category_alter_product_manufacture_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='manufacture',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manufacturers', to='catalog.manufacture'),
        ),
        migrations.AlterField(
            model_name='product',
            name='region',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='regions', to='catalog.region'),
        ),
        migrations.AlterField(
            model_name='product',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='types', to='catalog.type'),
        ),
    ]
