# Generated by Django 5.2 on 2025-04-22 18:31
from __future__ import annotations

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0006_alter_product_image"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={"ordering": ("name",), "verbose_name": "Products"},
        ),
    ]
