# Generated by Django 5.2 on 2025-04-29 20:28
from __future__ import annotations

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0008_alter_category_name_alter_product_name"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Category",
            new_name="ProductCategory",
        ),
        migrations.RenameModel(
            old_name="Manufacture",
            new_name="ProductManufacture",
        ),
        migrations.RenameModel(
            old_name="Region",
            new_name="ProductRegion",
        ),
        migrations.RenameModel(
            old_name="Sort",
            new_name="ProductSort",
        ),
        migrations.RenameModel(
            old_name="Type",
            new_name="ProductType",
        ),
    ]
