# Generated by Django 5.2 on 2025-06-23 18:42
from __future__ import annotations

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0010_rename_type_product_product_type"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={"ordering": ("name",), "verbose_name": "Product", "verbose_name_plural": "Products"},
        ),
        migrations.AlterModelOptions(
            name="productcategory",
            options={"verbose_name": "Product category", "verbose_name_plural": "Product categories"},
        ),
    ]
