server {
    listen 8088;
    charset utf-8;

    access_log  /app/www/coffeeshop/logs/coffeeshop_access.log;
    error_log   /app/www/coffeeshop/logs/coffeeshop_error.log error;

    location / {
        proxy_pass http://coffeeshop:8000;
        proxy_set_header Host $http_host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_redirect off;
    }

    location /static/ { root /app/www/coffeeshop; }
    location /media/ { root /app/www/coffeeshop; }
}
